# Generated by Django 6.0.1 on 2026-03-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScoreModelBasicWeight",
            fields=[
                ("model_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "established_year",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "registered_capital",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "actual_paid_capital",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "company_type",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "enterprise_size_type",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "social_security_count",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "website",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "business_scope",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_type",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "funding_round",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "patent_type",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "software_copyright",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "technology_enterprise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "db_table": "score_model_basic_weight",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ScoreModelProfessionalWeight",
            fields=[
                ("model_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "industry_market_size",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "industry_heat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "industry_profit_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "qualification",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "certificates",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "innovation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "partnership_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "ranking",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "db_table": "score_model_professional_weight",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ScoreModelTechWeight",
            fields=[
                ("model_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "tech_patent_type",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "patent_tech_attribute",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tech_software_copyright",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "software_copyright_tech_attribute",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tech_technology_enterprise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "industry_university_research",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "national_provincial_award",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "db_table": "score_model_tech_weight",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ScoreModelTotalWeight",
            fields=[
                ("model_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "model_weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "db_table": "score_model_total_weight",
                "managed": False,
            },
        ),
    ]
