# Generated by Django 6.0.1 on 2026-03-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AwardRanking",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "上榜榜单",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "资质认证",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "客户信息",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "企业基本信息",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "行业分类",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "专利信息",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "风险信息",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SoftwareCopyright",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "软件著作权",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "供应商",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ScoreLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enterprise_id",
                    models.IntegerField(blank=True, null=True, verbose_name="企业ID"),
                ),
                (
                    "enterprise_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="企业名称"
                    ),
                ),
                (
                    "score_type",
                    models.CharField(
                        choices=[
                            ("basic", "基础评分"),
                            ("tech", "科技属性评分"),
                            ("professional", "专业能力评分"),
                        ],
                        max_length=20,
                        verbose_name="评分类型",
                    ),
                ),
                ("score_value", models.IntegerField(verbose_name="评分值")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "评分日志",
                "verbose_name_plural": "评分日志",
            },
        ),
        migrations.CreateModel(
            name="ScoreResult",
            fields=[
                (
                    "enterprise_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "enterprise_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_score", models.IntegerField(default=0, verbose_name="总评分")),
                (
                    "basic_score",
                    models.IntegerField(default=0, verbose_name="基础评分"),
                ),
                (
                    "tech_score",
                    models.IntegerField(default=0, verbose_name="科技属性评分"),
                ),
                (
                    "professional_score",
                    models.IntegerField(default=0, verbose_name="专业能力评分"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "评分结果",
                "verbose_name_plural": "评分结果",
                "unique_together": {("enterprise_id", "enterprise_name")},
            },
        ),
    ]
