# Generated by Django 6.0.1 on 2026-03-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorelog",
            name="score_value",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="评分值"
            ),
        ),
        migrations.AlterField(
            model_name="scoreresult",
            name="basic_score",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="基础评分"
            ),
        ),
        migrations.AlterField(
            model_name="scoreresult",
            name="professional_score",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="专业能力评分"
            ),
        ),
        migrations.AlterField(
            model_name="scoreresult",
            name="tech_score",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="科技属性评分"
            ),
        ),
        migrations.AlterField(
            model_name="scoreresult",
            name="total_score",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="总评分"
            ),
        ),
    ]
