"""
Django settings for DjangoScoring project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-p@ns+)770$(dj$0+@w+_u+isqwarjoc8-9dr(2%h$ulj)lalfj"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'scoring', #评分模块
    'accounts', #用户管理、登录注册
    'weights', #评分权重设置
    'corsheaders',
    'rest_framework',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "DjangoScoring.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "DjangoScoring.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 使用 MySQL 后端
        'NAME': 'testdata',          # 你的数据库名称
        'USER': 'root',         # MySQL 用户名
        'PASSWORD': '88888888',     # MySQL 密码
        'HOST': 'localhost',                   # 数据库主机（本地通常是 localhost）
        'PORT': '3306',                        # MySQL 默认端口
        'OPTIONS': {
            'charset': 'utf8mb4',              # 支持 emoji 和完整 Unicode
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # 严格模式
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = False

# 允许前端开发服务器访问
#CORS_ALLOW_ALL_ORIGINS = True   # 为了开发方便，允许所有来源（生产环境请谨慎使用）
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    # 如果部署后有固定域名，也加上：
    # "https://your-frontend.com"
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), # 开发环境下设为1天 延长 Token 有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# 确保 Authorization 在允许的 Header 列表中
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'accept',
    'origin',
    'x-requested-with',
]

# 1. 允许跨域携带 Cookie
CORS_ALLOW_CREDENTIALS = True

# 3. 确保 Session Cookie 允许跨域（本地开发环境建议设置）
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = False  # 如果是 http 协议则设为 False

# 邮件配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'                # 如果是网易则为 smtp.163.com
EMAIL_PORT = 465                          # SMTP 端口
EMAIL_USE_SSL = True
EMAIL_HOST_USER = '**********@qq.com'      # 你的邮箱账号
EMAIL_HOST_PASSWORD = '**********'    # 注意：这里不是邮箱密码，是生成的“授权码”
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
