# Generated by Django 6.0.1 on 2026-03-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "domain_id",
                    models.AutoField(
                        db_column="domain_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="domain_name", max_length=50, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_column="domain_description", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", null=True
                    ),
                ),
            ],
            options={
                "db_table": "user_domains",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "code",
                    models.CharField(
                        db_column="invite_code",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_used", models.BooleanField(db_column="is_used", default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", null=True
                    ),
                ),
            ],
            options={
                "db_table": "user_dinvite_codes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "log_id",
                    models.AutoField(
                        db_column="log_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "operation_time",
                    models.DateTimeField(
                        auto_now_add=True, db_column="operation_time", null=True
                    ),
                ),
                ("action", models.CharField(db_column="action", max_length=50)),
            ],
            options={
                "db_table": "user_operation_logs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "role_id",
                    models.AutoField(
                        db_column="role_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(db_column="role_name", max_length=30, unique=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_column="role_description", null=True
                    ),
                ),
            ],
            options={
                "db_table": "user_roles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        db_column="user_id", primary_key=True, serialize=False
                    ),
                ),
                ("user_name", models.CharField(db_column="user_name", max_length=100)),
                (
                    "password_hash",
                    models.CharField(db_column="password_hash", max_length=60),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        db_column="email",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_column="phone",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, db_column="organization", max_length=100, null=True
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, db_column="position", max_length=100, null=True
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="registered_at", null=True
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, db_column="last_login_at", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updated_at", null=True
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "association_id",
                    models.AutoField(
                        db_column="association_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="assigned_at", null=True
                    ),
                ),
            ],
            options={
                "db_table": "user_and_roles",
                "managed": False,
            },
        ),
    ]
